---
title: "Untitled"
author: "TC"
date: "11/28/2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RNAmrf)
source(here::here("R/misc.R"))
library(dplyr)
```

```{r}

```



```{r}
filerscape=here::here("data/RFAM_PK//rscape.scores")

score_rscape= data.table::fread(filerscape)
names(score_rscape)=c("caseid","method","method2","SEN","PPV","F")
score_rscape=score_rscape[,-"method2"]
score_rscape[,3:5]=score_rscape[,3:5]/100

fileneff=here::here("data/RFAM_PK//neff.txt")

myneff=data.table::fread(fileneff)

names(myneff)=c("caseid","neff")

filenc=here::here("data/RFAM_PK//CLEN.txt")

mync=data.table::fread(filenc)

names(mync)=c("caseid","len")


fileapsi=here::here("data/RFAM_PK//apsi.txt")

myapsi=data.table::fread(fileapsi)


names(myapsi)=c("caseid","apsi")

filecomp=here::here("data/RFAM_PK/sci.scores")
score_trad= data.table::fread(filecomp,fill=TRUE)
names(score_trad)=c("method","caseid","SCI")
```



```{r}
filepkaln=here::here("data/RFAM_PK/RFAM.rds")

pkaln.all=readRDS(filepkaln)

rslt.all = lapply(pkaln.all,function(pkaln){
  try(bench_pkaln_2(pkaln))
})

rslt.df.s = do.call(rbind,rslt.all)
# names(rslt.df.s)=c(
#   "all",
#   "non-pair",
#   "all-bp",
#   "pk",
#   "non-pk",
#   "method",
#   "caseid"
# )

# rslt.df.1=dplyr::left_join(rslt.df.s,score_trad)

rslt.df.all=rslt.df.s %>% 
  # select(method,caseid, 1:5) %>% 
left_join(score_rscape) %>% 
  # left_join(score_trad) %>%
  left_join(myapsi) %>% 
  left_join(myneff) %>% 
  left_join(mync)  

rslt.contact= score_rscape %>% 
  left_join(score_trad) %>%
    left_join(myneff) %>% 
  left_join(mync)
  
  # dplyr::left_join(rslt.df.1,score_rscape)
# print(rslt.df.all,digits = 2)
```


```{r}
library(kableExtra)
library(dplyr)
```

```{r}
mytable= rslt.df.all %>% 
  select(method,caseid, contains("f1"),SEN,PPV,`F`,apsi,neff,len)


names(mytable)[3:7]= c(
  "All",
  "Loop",
  "Base-pair",
  "PK",
  "non-PK"
)

```



```{r}
mytable %>% 
  select(-caseid) %>% 
kable( booktabs = T,digits=2,longtable=TRUE) %>%
  # kable_styling() %>% 
   kable_styling(latex_options="scale_down")%>% 
  add_header_above(c(" ", "Alignment Accuracy (F1)" = 5, "Contact Pred"=3," "," "," ")) %>%
  pack_rows(index=table(mytable$caseid)) 
```



```{r}
rfam_tab_sel=mytable

save(rfam_tab_sel,file="~/GIT/thesis_tc/data/rfam_tab_sel.rda")
```

## figures


```{r}
library(tidyverse)
library(patchwork)
library(ggrepel)
```

```{r}
mytable.wide=
mytable %>% 
  pivot_wider(id_cols=c(caseid,len,neff),names_from=method,values_from=3:10)
```



```{r}
mytable.wide %>% 
  # filter(neff>40) %>% 
  ggplot(aes (x=All_cmalign,y=All_rnamrf,size=neff))+
  
  geom_point(aes(size=neff,color=neff>40))+
  # geom_point()+
  geom_abline()
```




```{r}
# wilcox.test(x,y, paired=TRUE)

with(mytable.wide %>% filter(neff > 40) ,wilcox.test(All_cmalign,All_rnamrf,paired=TRUE))


# with(mytable.wide %>% filter(neff > 40) ,wilcox.test(all_cmalign,all_rnamrf,paired=TRUE))
```



```{r}

myggdata=
mytable %>% 
  group_by(caseid) %>% 
  mutate(groupmax=method[which.max(PK)],
         diff=max(PK)-min(PK)) 
gg_pk2=
myggdata %>% 
  ggplot(aes(x=neff,y=PK,color=method)) +
  geom_point(size=3)+
  geom_line(aes(group=caseid,color=groupmax))+
  geom_label_repel(data=myggdata %>% filter(diff > 0.25, method == "rnamrf"), aes(label=caseid))+
  # stat_smooth()+
  scale_x_log10()
```


```{r}

pval=with(mytable.wide,wilcox.test(PK_rnamrf,PK_cmalign,paired=TRUE))

pval$p.value

data.filt = mytable.wide %>%
  filter(PK_rnamrf - PK_cmalign > 0.27)

gg_pk=
mytable.wide %>%
  ggplot(aes (x = PK_cmalign, y = PK_rnamrf,color = neff>40 )) +
  geom_point(, size=3) +
  geom_abline() +
    scale_color_discrete(name="",label=c("neff <= 40","neff > 40"))+
  # geom_point(data = data.filt, aes(size = neff),color="red") +
  geom_label_repel(data = data.filt,
                  aes(label = caseid))+
  xlab("F1 score for Pseudoknot alignment (cmalign MSA)")+
  ylab("F1 score for Pseudoknot alignment (RNAmrf MSA)")+
  lims(x=c(0,1),y=c(0,1))
  # annotate("text", x=0.5,y=1,label="P-value 0.03",color="red",size =6)

gg_pk
```

```{r}
# wilcox.test(x,y, paired=TRUE)
with(mytable.wide %>% filter(neff > 40),wilcox.test(PK_rnamrf,PK_cmalign,paired=TRUE,alternative = "greater"))

with(mytable.wide %>% filter(neff > 40),wilcox.test(All_rnamrf,All_cmalign,paired=TRUE,alternative = "greater"))
with(mytable.wide %>% filter(neff > 40),wilcox.test(`Loop_rnamrf`,`Loop_cmalign`,paired=TRUE,alternative = "greater"))

with(mytable.wide %>% filter(neff > 40),wilcox.test(`non-PK_rnamrf`,`non-PK_cmalign`,paired=TRUE,alternative = "greater"))
# mytable.wide$`non-pair_cmalign`
```

```{r}
# data.filt = mytable.wide %>%
  # filter(F_rnamrf - F_cmalign > 0.1)


mytable.wide %>% 
  ggplot(aes (x=All_cmalign,y=All_rnamrf,color=neff>40))+
  geom_point(aes(size=neff))+
  geom_label_repel(data = data.filt,
                  aes(label = caseid))+
  xlab("All column alignment accuracy (cmalign)")+
  ylab("All column alignment accuracy (MRFalign)")+
  # annotate("text", x=0.5,y=1,label="P-value 0.03",color="red",size =6)+

  
    geom_abline()
```

```{r}
mytable.wide$F_cmalign
```


```{r}

data.filt = mytable.wide %>%
  group_by(caseid) %>% 
  summarise(F_diff=F_rnamrf-F_cmalign) %>%
  ungroup() %>% 
  top_n(5,wt=F_diff)
  # filter(F_rnamrf - F_cmalign > 0.1)


mytable.wide %>% 
  ggplot(aes (x=F_cmalign,y=F_rnamrf,color=neff>40))+
  geom_point(aes(size=neff))+
  geom_label_repel(data = mytable.wide %>% filter(caseid %in% data.filt$caseid ),
                  aes(label = caseid))+
  xlab("Contact Prediction F1-score (cmalign)")+
  ylab("Contact Prediction F1-score (MRFalign)")+
  # annotate("text", x=0.5,y=1,label="P-value 0.03",color="red",size =6)+

  
    geom_abline()
```


```{r}
with(mytable.wide %>% filter(neff > 40),wilcox.test(F_rnamrf,F_cmalign,paired=TRUE,alternative = "greater"))


```

```{r}
library(tidyr)
```

```{r}
contact_wider=
rslt.contact %>% 
  pivot_wider(id_cols = c(caseid,neff,len),names_from=method,values_from=3:6)
```


```{r}
data.filt = contact_wider %>%
  filter(caseid %in% c("RF01725","RF02996"))
  # filter(SEN_rnamrf - SEN_cmalign > 0.15)
  

gg_cont_sens=
contact_wider %>% 
  # filter(neff>50) %>% 
  ggplot(aes (x = SEN_cmalign, y = SEN_rnamrf,color = neff>40 )) +
  geom_point(size=3) +
  geom_abline() +
    scale_color_discrete(name="",label=c("neff <= 40","neff > 40"))+
  # geom_point(data = data.filt, aes(size = neff),color="red") +
  geom_label_repel(data = data.filt,
                  aes(label = caseid))+
  xlab("Contact Prediction Sensitivity (cmalign MSA)")+
  ylab("Contact Prediction Sensitivity (RNAmrf MSA)")
gg_cont_sens
```

```{r}
with(mytable.wide %>% filter(neff > 40),wilcox.test(SEN_rnamrf,SEN_cmalign,paired=TRUE,alternative="greater"))
```

```{r}

ggplotColours <- function(n = 6, h = c(0, 360) + 15){
  if ((diff(h) %% 360) < 1) h[2] <- h[2] - 360/n
  hcl(h = (seq(h[1], h[2], length = n)), c = 100, l = 65)
}

mycolors = ggplotColours(3)
mylevels=c("rnamrf","cmalign","input")

ggdata_boxplot_contact =  rslt.contact %>% 
  pivot_longer(cols=3:5,names_to="metric") %>% 
  mutate(method=factor(method,
    levels=mylevels
  )) %>% 
  mutate(metric=factor(
    metric,
    levels=c("F",
  "SEN",
  "PPV"
  ),labels=c(
    "F-score",
  "Sensitivity",
  "Precision"
  )
  )) 


gg1=
ggdata_boxplot_contact %>% 
  # filter(neff>40) %>%
  mutate(neffcut=ifelse(neff>40,"neff > 40","neff <= 40 ")) %>% 
  # filter(mygroup == "Contact Prediction") %>% 
  ggplot(aes(x=metric,y=value,fill=method))+
  geom_boxplot()+
  scale_fill_manual(name="MSA",values=mycolors,limits=mylevels,labels=c("RNAmrf","cmalign","Reference"))+
  # scale_fill_manual(values=mycolors,limits=mylevels)+
  theme(axis.text.x=element_text(angle = 45,  hjust=1))+
  xlab("")+ggtitle("Contact Prediction")+facet_grid(.~neffcut)



gg1


ggdata_boxplot =

mytable %>% 
  # filter(neff>40) %>%
  pivot_longer(cols=3:8,names_to="metric") %>% 
  mutate(metric=factor(
    metric,
    levels=c(
  "All",
  "Loop",
  "Base-Pair",
  "non-PK",
  "PK",
  "SEN",
  "PPV",
  "F"
  ),labels=c(
  "all",
  "Loop",
  "Base-Pair",
  "non-Pseudoknot-bp",
  "Pseudoknot-bp",
  "Sensitivity",
  "Precision",
  "F1-score")
  )) %>%
  mutate(mygroup = ifelse(metric %in% c("Sensitivity","Precision","F1-score"),"Contact Prediction","Alignment Accuracy")) %>% 
  filter(metric !="SCI")

# ggplotColours(3)

gg2=
ggdata_boxplot %>% 

  mutate(neffcut=ifelse(neff>40,"neff > 40","neff <= 40 ")) %>% 
  mutate(method=factor(method,
    levels=mylevels
  )) %>% 
  filter(mygroup == "Alignment Accuracy") %>%
  ggplot(aes(x=metric,y=value,fill=method))+
  geom_boxplot()+
  scale_fill_manual(name="MSA",values=mycolors,limits=mylevels,labels=c("RNAmrf","cmalign","Reference"))+
  
  labs(x="",y="")+ggtitle("Alignment Accuracy")+facet_grid(.~neffcut)
#+
  # theme(legend.position="none")
  # facet_grid(.~mygroup)


# gg2
# gg1+gg2
gg1+gg2+plot_layout(guides="collect")&theme_classic()&theme(axis.text.x=element_text(angle = 45,  hjust=1))
```


```{r}

contact_wider=
rslt.contact %>% 
  
  pivot_wider(id_cols=c(caseid,len,neff),names_from=method,values_from=3:6)

  with(contact_wider %>% filter(neff > 40),wilcox.test(F_rnamrf,F_cmalign,paired=TRUE,alternative = "greater"))
  
    with(contact_wider %>% filter(neff > 40),wilcox.test(F_rnamrf,F_input,paired=TRUE,alternative = "greater"))
    
      with(contact_wider %>% filter(neff > 40),wilcox.test(F_input,F_cmalign,paired=TRUE,alternative = "greater"))
```

```{r}

  with(contact_wider %>% filter(neff > 40),wilcox.test(SEN_rnamrf,SEN_cmalign,paired=TRUE,alternative = "greater"))
  
    with(contact_wider %>% filter(neff > 40),wilcox.test(SEN_rnamrf,SEN_input,paired=TRUE,alternative = "greater"))
    
      with(contact_wider %>% filter(neff > 40),wilcox.test(SEN_input,SEN_cmalign,paired=TRUE,alternative = "greater"))
```




```{r fig.height=9}
rfam_patch2=gg2+gg_pk+gg1+gg_cont_sens+plot_layout(guides="collect",byrow = FALSE) +plot_annotation(tag_levels = "A")& theme_classic() & theme(axis.text.x=element_text(angle=45,hjust = 1))

rfam_patch2
```


```{r}

save(rfam_patch2,file="~/GIT/thesis_tc/data/rfam_patch2.rda")
```

### contaa

```{r}


testdirs=list.dirs(here::here("data/RFAM_PK/RFAM/"),recursive=FALSE)

# testdirs

testdirs.filt=testdirs[basename(testdirs) %in% c("RF01725","RF02996")]

names(testdirs.filt) =basename(testdirs.filt)

testdirs.filt
```

```{r}

# plot_rscape=function(dir.path)
# list.files(testdirs.filt[[1]],pattern="*sorted.cov",recursive = TRUE)
```




```{r}
plot_rscape = function(cov.path) {
  ggdata =
    data.table::fread(cov.path,
                      skip = 6) %>%
    mutate(V6=ifelse(V5 < 0.05, 1,0),
           result=NA,
           result=ifelse(V5<0.05 & V1=="*", "TP",result),
           result=ifelse(V5<0.05 & V1 !="*", "FP",result))
    # mutate(V5=ifelse(V5==0, 2e-16,V5)) #%>% 
    # mutate(V5 = ifelse(V5 > 10, 10, V5))
  
  maxl=max(ggdata$V2)
  
  gg =
    ggplot(ggdata)  +
    geom_tile(data = ggdata %>% filter(V1 == "*"), aes(x = V2, y = V3)) + coord_fixed() +
    geom_tile(data = ggdata %>% filter(V6==1), aes(x = V3, y = V2, fill=result))+
  labs(x = "Alignment index", y = "Alignment index") +
    lims(x=c(0,maxl),y=c(0,maxl))+
    scale_fill_manual(values=c(FP="red",TP="blue"),limits=c("FP","TP"))
  return(gg)
}




```


```{r}

gg_cont1=
plot_rscape(here::here("data/RFAM_PK/RFAM/RF01725/rnamrf/rnamrf.sorted.cov"))+ ggtitle("RNAmrf",subtitle ="FP:0 TP:20 True:29 Found:20" )+
    annotate("rect",xmin=80,xmax=94,ymin=40,ymax=55,alpha=0.1,color="red")


gg_cont2=
plot_rscape(here::here("data/RFAM_PK/RFAM/RF01725/cmalign/cmalign.sorted.cov"))+
   ggtitle("cmalign",subtitle ="FP:0 TP:15 True:29 Found:15" )

gg_cont1+gg_cont2
```

```{r}
gg_cont3=
plot_rscape(here::here("data/RFAM_PK/RFAM/RF02996/rnamrf/rnamrf.sorted.cov"))+
   ggtitle("RNAmrf",subtitle ="FP:7 TP:22 True:23 Found:29" )+
  theme(legend.position = "none")+
    annotate("rect",
             xmin=62,xmax=70,ymin=35,ymax=45,alpha=0.1,color="red")


gg_cont4=
plot_rscape(here::here("data/RFAM_PK/RFAM/RF02996/cmalign/cmalign.sorted.cov"))+
   ggtitle("cmalign",subtitle ="FP:4 TP:16 True:23 Found:20" )

gg_cont3+gg_cont4
```


```{r}


library(R4RNA)

ss1 = R4RNA::readVienna(here::here("data/RFAM_PK/RFAM/RF01725/seq.ss"))
ss1_col = colourByUnknottedGroups(ss1, c("blue","red"),get=TRUE)

ss2 = R4RNA::readVienna(here::here("data/RFAM_PK/RFAM/RF02996/seq.ss"))
ss2_col = colourByUnknottedGroups(ss2, c("blue","red"),get=TRUE)


library(patchwork)

patch_ss=
  wrap_elements(~plotHelix(ss1_col)) +ggtitle("RF01725")+
  wrap_elements(~plotHelix(ss2_col)) +ggtitle("RF02996")

patch_ss
  
```


```{r}
# gg_cont1+gg_cont2+patchwork::wrap_elements()

rfam_patch3=
  wrap_elements(~plotHelix(ss1_col),ignore_tag=TRUE) +
  ggtitle("RF01725")+
  gg_cont1+gg_cont2+
  wrap_elements(~plotHelix(ss2_col),ignore_tag=TRUE)+
  ggtitle("RF02996")+
  gg_cont3+gg_cont4+
  plot_layout(guides="collect") + plot_annotation(tag_levels="A") & theme_classic() &theme(legend.position="right") 

# patch_rscape


rfam_patch3
```


```{r}

save(rfam_patch3,file="~/GIT/thesis_tc/data/rfam_patch3.rda")
```

