---
title: "Untitled"
author: "TC"
date: "11/27/2020"
output: bookdown::pdf_document2
---

```{r setup, include=FALSE}
# bookdown::pdf_document2()
knitr::opts_chunk$set(echo = TRUE)
library(RNAmrf)
source(here::here("R/misc.R"))
library(dplyr)

library(kableExtra)
```

## R Markdown

```{r}
filerscape=here::here("data/simulation/simulation.rscape.scores")

score_rscape= data.table::fread(filerscape)

names(score_rscape)=c("caseid","method","method2","SEN","PPV","F")

score_rscape=score_rscape[,-"method2"]

score_rscape[,3:5]=score_rscape[,3:5]/100

score_rscape %>% filter(method!="input")
```

```{r}
# filecomp=here::here("data/synthetic/compalignp.scores")

# score_trad= data.table::fread(filecomp)
# names(score_trad)=c("method","caseid","SPS","SCI")
```


```{r}
filepkaln=here::here("data/simulation/simulation.rds")

pkaln.all=readRDS(filepkaln)

rslt.all = lapply(pkaln.all,function(pkaln){
  try(bench_pkaln_2(pkaln))
})

rslt.df.s = do.call(rbind,rslt.all)
# names(rslt.df.s)=c(
#   "all",
#   "non-pair",
#   "all-bp",
#   "pseudoknot",
#   "non-pseudoknot",
#   "method",
#   "caseid"
# )

# rslt.df.1=dplyr::left_join(rslt.df.s,score_trad)

rslt.df.all=rslt.df.s %>% 
 select(method,caseid,contains("pair") & !contains("mcc")) %>% 
  # left_join(score_trad) %>% 
left_join(score_rscape)
  
  # dplyr::left_join(rslt.df.1,score_rscape)
print(rslt.df.all,digits = 2)
```

```{r}
synth_tab=rslt.df.all

synth_tab
```


```{r}

```

```{r}
synth_tab_sel=
synth_tab %>% 
  filter(!grepl("ssmrf",method)) %>% 
  filter(caseid %in% c("simulation_1","simulation_2","simulation_3","simulation_4")) %>% 
  select(method,caseid, contains("pair_pk"),contains("pair_nonpk"),contains("pair_all"),SEN,PPV,`F`)

# names(synth_tab_sel)[3:11]= rep(c("SEN","PREC","F1"))
synth_tab_sel

```


```{r}
synth_tab_sel %>% 
  select(-caseid) %>% 
kable( booktabs = T,digits=2,
       col.names=c("method",rep(c("SEN","PPV","F1"),4))) %>%
  kable_styling() %>%
  add_footnote(
    c("PK: Pseudoknot.",
      "SEN: Sensitivity. PPV: Precision. F1: F1-score")
  ) %>% 
  add_header_above(c(" ", "PK alignment" = 3,"non-PK alignment"=3,"PK+non-PK"=3,"Contact Prediction"=3)) %>%
    pack_rows(index=table(synth_tab_sel$caseid)) %>% 
  column_spec(4,bold=T)
```



```{r}
# save(synth_tab_sel,file="~/GIT/thesis_tc/data/synth_tab_sel.rda")
```




## figure

```{r}
library(ggplot2)
library(patchwork)
```

```{r}


testdirs=list.dirs(here::here("data/simulation/simulation/"),recursive=FALSE)

# testdirs

testdirs.filt=testdirs[basename(testdirs) %in% c("simulation_1","simulation_2","simulation_3","simulation_4")]

names(testdirs.filt) =basename(testdirs.filt)

# testdirs.filt
```


```{r}
plot_rscape = function(cov.path) {
  ggdata =
    data.table::fread(cov.path,
                      skip = 6) %>%
    mutate(V6=ifelse(V5 < 0.05, 1,0),
           result=NA,
           result=ifelse(V5<0.05 & V1=="*", "TP",result),
           result=ifelse(V5<0.05 & V1 !="*", "FP",result))
    # mutate(V5=ifelse(V5==0, 2e-16,V5)) #%>% 
    # mutate(V5 = ifelse(V5 > 10, 10, V5))
  
  gg =
    ggplot(ggdata)  +
    geom_tile(data = ggdata %>% filter(V1 == "*"), aes(x = V2, y = V3)) + coord_fixed() +
    geom_tile(data = ggdata %>% filter(V6==1), aes(x = V3, y = V2, fill=result))+
  labs(x = "Alignment index", y = "Alignment index") +
    theme(legend.position = "none")+
    scale_fill_manual(values=c(FP="red",TP="blue"),limits=c("FP","TP"))
  return(gg)
}

names(testdirs.filt)=c(
  "Simulation-1",
  "Simulation-2",
  "Simulation-3",
  "Simulation-4"
)
```


```{r}
gglists=lapply(1:length(testdirs.filt),function(i){
  
  caseid=names(testdirs.filt)[i]
  path=testdirs.filt[i]
  gglist=list()
  gglist$cmalign=plot_rscape(paste0(path,"/cmalign/cmalign.sorted.cov"))+
    ggtitle(label="",subtitle = "cmalign")
  gglist$rnamrf=plot_rscape(paste0(path,"/rnamrf/rnamrf.sorted.cov"))+
    ggtitle(label="",subtitle="RNAmrf")
  return(gglist)
})


```

```{r}


library(R4RNA)
library(ggplot2)

ss1 = R4RNA::readVienna(here::here("data/simulation/simulation/simulation_1/seq1000_gaps.ss"))
ss1_col = colourByUnknottedGroups(ss1, c("blue","red"),get=TRUE)

ss2 = R4RNA::readVienna(here::here("data/simulation/simulation/simulation_2/seq1000_gaps.ss"))
ss2_col = colourByUnknottedGroups(ss2, c("blue","red"),get=TRUE)

ss3 = R4RNA::readVienna(here::here("data/simulation/simulation/simulation_3/seq1000_gaps.ss"))

ss3_col = colourByUnknottedGroups(ss3, c("blue","red"),get=TRUE)

ss4 = R4RNA::readVienna(here::here("data/simulation/simulation/simulation_4/seq1000_gaps.ss"))
ss4_col = colourByUnknottedGroups(ss4, c("blue","red"),get=TRUE)



library(png)
library(grid)
library(patchwork)
pk_h = readPNG("~/GIT/thesis_tc/figure/pk_H.png")
pk_hhh = readPNG("~/GIT/thesis_tc/figure/pk_HHH.png")
pk_hlout = readPNG("~/GIT/thesis_tc/figure/pk_HLout.png")
pk_ll = readPNG("~/GIT/thesis_tc/figure/pk_LL.png")

# grid.raster(img)
gpk_h=rasterGrob(pk_h)
gpk_hhh=rasterGrob(pk_hhh)
gpk_hlout=rasterGrob(pk_hlout)
gpk_ll=rasterGrob(pk_ll)


patch_ss=
  wrap_elements(~plotHelix(ss1_col)) +ggtitle("Simulation-1 (PKtype: H)")+
  gpk_h+
  wrap_elements(~plotHelix(ss2_col)) +ggtitle("Simulation-2 (PKtype: HHH)")+
  gpk_hhh+
  wrap_elements(~plotHelix(ss3_col)) +ggtitle("Simulation-3 (PKtype: Hlout)")+
  gpk_hlout+
  wrap_elements(~plotHelix(ss4_col)) +ggtitle("Simulation-4 (PKtype: LL)")+
    gpk_ll+
  plot_layout(ncol=2)

patch_ss
  
```



```{r}

library(png)
library(grid)
library(patchwork)

ss1 = readPNG("~/GIT/thesis_tc/figure/simss1.png")
ss2 = readPNG("~/GIT/thesis_tc/figure/simuss2.png")
ss3 = readPNG("~/GIT/thesis_tc/figure/simuss3.png")
ss4 = readPNG("~/GIT/thesis_tc/figure/simuss4.png")
# grid.raster(img)
grob_ss1=rasterGrob(ss1)
grob_ss2=rasterGrob(ss2)
grob_ss3=rasterGrob(ss3)
grob_ss4=rasterGrob(ss4)

wrap_elements(grob_ss1)
```

```{r fig.height=8,fig.width=5}
# patch_rscape=
#   (gglists[[1]]$rnamrf+ gglists[[1]]$cmalign)/
#   (gglists[[2]]$rnamrf+ gglists[[2]]$cmalign)/
#   (gglists[[3]]$rnamrf+ gglists[[3]]$cmalign)+
#    plot_annotation(tag_levels = 'A') +
#   plot_layout()
  
patch_rscape=
  wrap_elements(grob_ss1,ignore_tag=TRUE)+ggtitle("Simulation-1",subtitle="H")+
  gglists[[1]]$rnamrf+gglists[[1]]$cmalign+
  wrap_elements(grob_ss2,ignore_tag=TRUE)+ggtitle("Simulation-2",subtitle="HHH")+
  gglists[[2]]$rnamrf+gglists[[2]]$cmalign+
  wrap_elements(grob_ss3,ignore_tag=TRUE)+ggtitle("Simulation-3",subtitle="HLout")+
  gglists[[3]]$rnamrf+gglists[[3]]$cmalign+
  wrap_elements(grob_ss4,ignore_tag=TRUE)+ggtitle("Simulation-4",subtitle="LL")+
  gglists[[4]]$rnamrf+gglists[[4]]$cmalign +
  
  plot_layout(ncol=3,guides="collect", widths=c(1,1,1)) & theme_classic() & theme(legend.position="bottom") 

patch_rscape
```


```{r}
patch_rscape=patch_rscape
save(patch_rscape,file="~/GIT/thesis_tc/data/patch_rscape.rda")
```

```{r}
patch_ss
```


```{r}
save(patch_ss,file="~/GIT/thesis_tc/data/patch_ss.rda")
```








