---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library(RNAmrf)

suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(dplyr))
library(ggplot2)

```

## R Markdown

```{r}
## renumber
read_mrf_renum = function(filemrf) {
  
  myalphabet = c("a", "u", "c", "g", "-")
  
  v1 = data.table::fread(cmd = paste("grep '^V'", filemrf))
  names(v1)[-1] = myalphabet
  
  w1 = data.table::fread(cmd = paste("grep  '^W'", filemrf))
  
  
  len=nrow(v1)
  len_a=length(myalphabet)
  
  # renumber MRF
  
  v1$i_ori=as.integer(gsub(".*\\[(.*?)\\].*","\\1",v1$V1))
  v1$i=1:nrow(v1)
  
  
  w1$i_ori=as.integer(gsub(".*\\[(.*?)\\]\\[(.*?)\\].*","\\1",w1$V1))
  w1$i=match(w1$i_ori,v1$i_ori)
  
  w1$j_ori=as.integer(gsub(".*\\[(.*?)\\]\\[(.*?)\\].*","\\2",w1$V1))
  w1$j=match(w1$j_ori, v1$i_ori)
  
  array_j = array(0, dim = c(len, len, len_a, len_a))
  
  for (m in 1:nrow(w1)) {
    id_i = w1$i[m]
    id_j = w1$j[m]
    
    mat = matrix(as.matrix(w1[m, 2:26]), 5, 5, byrow = TRUE)
    array_j[id_i, id_j, , ] = mat
    
  }
  
  ids = expand.grid(1:nrow(v1), 1:nrow(v1)) %>% filter(Var2 > Var1) %>% arrange(Var1)
  w1_mat = as.matrix(w1[, 2:(1 + length(myalphabet) * length(myalphabet))])
  
  mat_score = sapply(1:nrow(w1_mat), function(i) {
    tmpmat = matrix(w1_mat[i,], 5, 5)
    score = sqrt(sum(tmpmat[-5,-5] ^ 2))
    return(score)
  })
  ids$score = mat_score
  
  mat_mrf = matrix(0, nrow(v1), nrow(v1))
  
  mat_mrf[as.matrix(ids[, c(1, 2)])] = ids[, 3]
  mat_mrf[as.matrix(ids[, c(2, 1)])] = ids[, 3]
  
  mat_apc = RNAmrf:::APC_correction(mat_mrf)
  
  mrf = list(
    len = len,
    h = v1,
    j = w1,
    mat_mrf = mat_mrf,
    mat_apc = mat_apc,
    array_j=array_j
  )
  mrf_mat=RNAmrf:::mrf2mrf_mat(mrf)
  mrfh = as.matrix((mrf$h[, 2:6]))
  
  mrf$mrf_mat=mrf_mat
  mrf$mrf_h=mrfh
  
  return(mrf)
}

pair_a2b2aln = function(a2b_1, a2b_2, seqs) {

  last_idx = -1
  for (i in 1:length(a2b_1)) {
    if (a2b_1[i] == -1) {
      a2b_1[a2b_1 > last_idx] = a2b_1[a2b_1 > last_idx] + 1
      a2b_2[a2b_2 > last_idx] = a2b_2[a2b_2 > last_idx] + 1
      a2b_1[i] = last_idx + 1
    }
    last_idx = a2b_1[i]
  }
  
  last_idx = -1
  for (i in 1:length(a2b_2)) {
    if (a2b_2[i] == -1) {
      a2b_1[a2b_1 > last_idx] = a2b_1[a2b_1 > last_idx] + 1
      a2b_2[a2b_2 > last_idx] = a2b_2[a2b_2 > last_idx] + 1
      a2b_2[i] = last_idx + 1
    }
    last_idx = a2b_2[i]
  }
  
  a2b_1_1b=a2b_1+1
  a2b_2_1b=a2b_2+1
  seq_aln1 = character(max(a2b_1_1b, a2b_2_1b))
  seq_aln1[] = "-"
  seq_aln2 = character(max(a2b_1_1b, a2b_2_1b))
  seq_aln2[] = "-"
  
  seq_aln1[a2b_1_1b] = seqs[[1]]
  seq_aln2[a2b_2_1b] = seqs[[2]]
  
  return(list(
    seq_aln1=seq_aln1,
    seq_aln2=seq_aln2
  ))
}
```


```{r}

mymrf=read_mrf_renum(filemrf)
```

```{r}

filemrf="/home/tc/GIT/sandbox/mrftmp/mrf/5_8S_rRNA/tmp.sto.afa.mrf"

fileout="/home/tc/GIT/sandbox/mrftmp/mrf/5_8S_rRNA/"

fileseqs="/home/tc/GIT/sandbox/mrftmp/5_8S_rRNA/"

seqfiles=list.files(fileseqs,pattern = "raw")
```


```{r}

dummy = pbapply::pblapply(seqfiles, function(seqfile) {
  seqs = seqinr::read.fasta(file.path(fileseqs, seqfile))
  
  a2b_1 = align_seq2mrf(seqs[[1]], mymrf, wt_h = 0.5, debug = FALSE)
  a2b_2 = align_seq2mrf(seqs[[2]], mymrf, wt_h = 0.5, debug = FALSE)
  seqaln = pair_a2b2aln(a2b_1, a2b_2, seqs = seqs)
  
  seqinr::write.fasta(seqaln,
                      names = names(seqs),
                      file.out = file.path(fileout, paste0(seqfile, ".mrfaln.fa")))
})

```

## benchit

```{r}
rslt=data.table::fread("~/GIT/sandbox/mrftmp/mrf/5_8S_rRNA/benchmark.tbl")
```

```{r}
rslt$apsi=as.numeric(gsub(".*apsi-(.*?).sci.*","\\1",rslt$V1))

ggplot(rslt)+
  geom_point(aes(apsi, V2))+
  ylim(0,1)
```

```{r}
rslt_mafft= data.table::fread("~/GIT/RNA_PKALN/data/bralibase_2.1/scores_ref/mafft/k2.5_8S_rRNA.mafft_ginsi.list.coal.sci.apsi")

rslt_mafft$apsi=as.numeric(gsub(".*apsi-(.*?).sci.*","\\1",rslt_mafft$V1))

ggplot(rslt_mafft)+
  geom_point(aes(apsi,V5))+
    ylim(0,1)
```

```{r}
rslt_mafft2=
rslt_mafft %>% mutate(id=gsub("(.*raw).*","\\1",basename(V4))) %>% 
  select(id,mafft=V5)


gg1=
rslt %>% mutate(id =gsub("(.*raw).*","\\1",V1)) %>% 
  select(id,mrfaln=V2,apsi) %>% 
  left_join(rslt_mafft2) %>% 
  ggplot(aes(mrfaln,mafft,color=apsi<60))+geom_point()+geom_abline()+lims(x=c(0.5,1),y=c(0.5,1))
```



```{r}
bench=data.table::fread("/home/tc/GIT/sandbox/mrftmp/mrfonly/Cobalamin/benchmark.tbl")

bench_ref=data.table::fread("~/GIT/RNA_PKALN/data/bralibase_2.1/scores_ref/mafft/k2.Cobalamin.mafft_ginsi.list.coal.sci.apsi")

bench_ref$apsi=as.numeric(gsub(".*apsi-(.*?).sci.*","\\1",bench_ref$V1))

ggplot(bench_ref)+
  geom_point(aes(apsi,V5))+
    ylim(0,1)

bench_ref2=bench_ref %>% 
  select(V4, V5,V6,V7) %>% 
  mutate(V4=basename(V4))


# ("~/GIT/sandbox/mrftmp/mrf/5_8S_rRNA/benchmark.tbl")
bench_ref2=
bench_ref %>% mutate(id=gsub("(.*raw).*","\\1",basename(V4))) %>% 
  select(id,mafft=V5)


gg2=
bench %>% mutate(id =gsub("(.*raw).*","\\1",V1)) %>% 
  mutate(apsi=as.numeric(gsub(".*apsi-(.*?).sci.*","\\1",V1))) %>% 
  select(id,mrfaln=V2,apsi) %>% 
  left_join(bench_ref2) %>% 
  ggplot(aes(mrfaln,mafft,color=apsi<50))+geom_point()+geom_abline()+lims(x=c(0.5,1),y=c(0.5,1))

# 
# bench$apsi=as.numeric(gsub(".*apsi-(.*?).sci.*","\\1",bench$V1))
# 
# ggplot(bench)+
#   geom_point(aes(apsi, V2))+
#   ylim(0,1)
gg2


```

```{r}
save(gg1,gg2,file = "~/tmp.rda")
```


