---
title: "Untitled"
author: "TC"
date: "11/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RNAmrf)
```

## R Markdown

```{r}

pairs=rep(0,30)

pairs[1:4]=15:12
pairs[6:9]=28:25
pairs

ss=rep(".",30)
ss[1:4]="("
ss[15:12]=")"
ss[6:9]="A"
ss[28:25]="a"

seqss=seqinr::c2s(ss)
seqss
```

```{r}
j_pair=structure(c(-1.30412, 3.96785, -1.30474, -1.31304, -0.00854209,
3.91698, -1.30412, -1.29931, -1.2937, -0.00849558, -1.2937, -1.31304, 
-1.28455, 3.86993, -0.00847145, -1.29931, -1.30474, 3.91198, 
-1.28455, -0.00840413, -0.00849558, -0.00854209, -0.00840413, 
-0.00847145, 0))

h_single=c(1,1,1,1,-4)
```

```{r}
ss
```

```{r}
ss2mrf = function(ss) {
  j_pair = structure(
    c(
      -1.30412,
      3.96785,-1.30474,-1.31304,-0.00854209,
      3.91698,-1.30412,-1.29931,-1.2937,-0.00849558,-1.2937,-1.31304,
      -1.28455,
      3.86993,-0.00847145,-1.29931,-1.30474,
      3.91198,
      -1.28455,-0.00840413,-0.00849558,-0.00854209,-0.00840413,
      -0.00847145,
      0
    )
  )
  
  h_single = c(1, 1, 1, 1,-4)
  
  
  df.pair = RNAmrf:::ss2pairs(ss)
  line_h = sprintf("V[%d] %s", df.pair$id - 1, paste0(h_single, collapse =
                                                        " "))
  
  df.pair.tmp = df.pair[df.pair$pair > df.pair$id, ]
  
  line_v = sprintf("W[%d][%d] %s",
                   df.pair.tmp$id - 1,
                   df.pair.tmp$pair - 1,
                   paste0(j_pair, collapse = " "))
  
  mrflines = c(line_h, line_v)
  
  return(mrflines)
  
}
```




```{r}
fsto="/home/tc/GIT/RNA_PKALN/data/RFAM_PK/RF00028/RF00028.sto"

```

```{r}
dfref=RNAmrf:::read_dfref(fsto)

mrflines=ss2mrf(dfref$ss)
```

