---
title: "Untitled"
author: "TC"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Matrix)
library(dplyr)
library(ggplot2)
source("../R/isorank.R")
```

## R Markdown




```{r}
mat1=matrix(
  0, 5,5
)
rownames(mat1)=letters[1:5]
colnames(mat1)=letters[1:5]
links=data.table::fread(
"
from to
1 2
2 3
3 4
3 5
"
)

mat1[as.matrix(links[,c(1,2)])]=1
mat1[as.matrix(links[,c(2,1)])]=1
mat1
# mat1[]

```


```{r}
mat2=matrix(
  0, 5,5
)
rownames(mat2)=1:nrow(mat2)

links2=data.table::fread(
"
from to
1 2
2 3
3 4
3 5
"
)

mat2[as.matrix(links2[,c(1,2)])]=1
mat2[as.matrix(links2[,c(2,1)])]=1
mat2
```


```{r}
mat1.graph=mat2graph(mat1)

mat2.graph=mat2graph(mat2,id_renum=1000)

mat1.graph$nodes$group="1"

mat2.graph$nodes$group="2"

nodes=rbind(mat1.graph$nodes,mat2.graph$nodes)

edges=rbind(mat1.graph$edges,mat2.graph$edges)

# visNetwork::visNetwork(mat2.graph$nodes, mat2.graph$edges, width="100%", height="400px")

visNetwork::visNetwork(nodes, edges, width="100%", height="450px")
```







```{r}
Rmat=run_isorank(mat1,mat2)

gg_mat(Rmat)
extract_aln(Rmat)
```



```{r}
visNetwork::visNetwork(nodes, edges, width="100%",height="450px")
```

