---
title: "Untitled"
author: "TC"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(Rcpp)
source(here::here("R/apc.R"))
source(here::here("R/isorank.R"))
source(here::here("R/mapalign.R"))
sourceCpp(here::here("src/mapalignR.cpp"))
```

```{r}

mrf=read_mrf("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")

ct_ref=RNASSP::read_ct("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/3VRS_A.ct")

seqs=seqinr::read.fasta("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.ungapped.msa")

mrf_mat=mrf2mrf_mat(mrf)


   seq=seqs[[1304]]
```


```{r}
mrfapc.df=as.data.frame(which(!is.na(mrf$mat_apc), arr.ind = TRUE))

mrfapc.df$val= mrf$mat_apc[which(!is.na(mrf$mat_apc))]

mrf.top10 = 
mrfapc.df %>% filter(col >row) %>% arrange(desc(val)) %>% top_n(10)

len_a=5

mrf_mat.masktop10 = mrf_mat

mrf_mat.masktop10[]=0

for (m in 1:nrow(mrf.top10)){
    id_i = mrf.top10$row[m]
    id_j = mrf.top10$col[m]
    
    id_ia = id2_to_id1(1, id_i, len_a)
    id_ja = id2_to_id1(1, id_j, len_a)
    
    mrf_mat.masktop10[id_ia:(id_ia + len_a - 1), id_ja:(id_ja + len_a - 1)]=1
    
    mrf_mat.masktop10[id_ja:(id_ja + len_a - 1), id_ia:(id_ia + len_a - 1)]=1
}

mrf_mat.masked= mrf_mat * mrf_mat.masktop10
```




```{r}
    exp_seq = encode_seq(seq)
mrfh=as.matrix((mrf$h[,2:6]))
    
    SCO = ini_SCO(
      seq = exp_seq$seq_int_ungapped,
      mrf_mat = mrf_mat, 
      mrf_h = mrfh,
      mrf_len = mrf$len,
      sep_x = 0,
      sep_y = 1
    )
    
    # align_R(SCO,debug = TRUE)
    
     gg_mat(SCO)
```


```{r}
SCO2= ini_SCO_simple(exp_seq$seq_int_ungapped,
                     mrf_h=mrfh)

    # align_R(SCO2)
    
     gg_mat(SCO2)
```

```{r}
a2b = align(SCO2,0.1,-1)
score_aln(a2b,seq = exp_seq$seq_int_ungapped, mrf_mat = mrf_mat, mrf_h = mrfh)
```


```{r}
SCO_mod=mod_SCO(SCO2,iteration=20,exp_seq$seq_int_ungapped, mrf_mat=mrf_mat,mrf_h=mrfh)
```

```{r}
all(SCO_mod==SCO2)
```


```{r}
gg_mat(SCO_mod)
gg_mat(SCO2)
```


```{r}

```




```{r}

a2b_init = align(SCO,gap_open=-1,gap_ext=0.1)

a2b_sco = align(SCO_mod, gap_open=-1,gap_ext=0.1)

score_aln(a2b_init, exp_seq$seq_int_ungapped, mrf_mat,mrfh)

score_aln(a2b_sco, exp_seq$seq_int_ungapped, mrf_mat,mrfh)
score_aln(exp_seq$seq_int_ref-1, exp_seq$seq_int_ungapped, mrf_mat,mrfh)
```






```{r}
a2b =exp_seq$seq_int_ref

a2b

a2b2seq= function(a2b,seq,len){
  seq_aln = character(len)
  seq_aln[] = "-"
  
  seq_aln[a2b[a2b>0]] = seq[a2b > 0]
  return(seq_aln)

}


a2b2seq(a2b, seq=exp_seq$seq_ungapped, len=length(seqs[[1]]))
seqs[[2]]
```


```{r}

seq_init=a2b2seq(align_R(SCO2), exp_seq$seq_ungapped, len=length(seqs[[1]]))
seq_aln = a2b2seq(align_R(SCO_mod), exp_seq$seq_ungapped, len=length(seqs[[1]]))
seq_ref =a2b2seq(exp_seq$seq_int_ref, exp_seq$seq_ungapped, len=length(seqs[[1]]))

# seq_ini

seq_aln %>% seqinr::c2s()
seq_ref %>% seqinr::c2s()

seq_init %>% seqinr::c2s()
```

```{r}


bench_aln(seq_init,seqref=seqs[[1]],ctref=ct_ref)

bench_aln(seq_aln,seqref=seqs[[1]],ctref=ct_ref)

bench_aln(seqs[[1304]],seqref=seqs[[1]],ctref=ct_ref)


```

##

mapalign is working

