---
title: "Untitled"
author: "TC"
date: "2/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r}
source("~/GIT/rna_ml/R/IO_funs.R")

dca= read_dca("~/GIT/RNA_SSMC/data/spotrna_RNAcmap_neff1/1P6V_B/inf.a2m.ungapped.gremlincpp")

ct= RNASSP::read_ct("~/GIT/RNA_SSMC/data/spotrna_RNAcmap_neff1/1P6V_B/ref.ct")
```

```{r}
plot_dca = function(dca) {
  `%>%`=magrittr::`%>%`
  names(dca)[3]="score"
  len=max(dca$V2)
  
  gg = 
    dca %>% 
    dplyr::filter(score >0.5) %>% 
    ggplot2::ggplot() + 
    ggplot2::geom_tile(ggplot2::aes(V1,V2, color = score)) +
    ggplot2::geom_abline() +
    ggplot2::lims(x = c(1,len), y = c(1, len)) +
    ggplot2::coord_fixed()
return(gg)

}

plot_dca(dca)
```

```{r}
tcol_to_mat = function(V1,V2, V3, mydim = NA){
  df = data.frame(V1=V1,V2=V2,V3=V3, stringsAsFactors=FALSE)
  mat1 = reshape2::acast(df, V1~V2, value.var = "V3", fill=0)
  if(is.na(mydim)){
    mydim = max(df$V1,df$V2)
  }
  mat2 = matrix(0, mydim,mydim)
  mat2[1:(mydim-1),2:mydim] = mat1
  mat3 = mat2 + t(mat2)
  return(mat3)
}
```

```{r}
dca.mat=tcol_to_mat(dca$V1,dca$V2,dca$score_gremlin_cpp)

seq=ct$nt 
```

```{r}
a2b=matrix(nrow=length(seq),ncol=ncol(dca.mat))
```

```{r}
align_seq2dca=function(seq,dca.mat){
  seed
  
  
}
```

```{r}
seqa=seq

seqb= c(seq[1:5],seq[10:15], seq[20:68])


```


```{r}
mat = matrix(0,length(seqa),length(seqb))
```


```{r}
for(i in 1:nrow(mat)){
  for (j in 1:ncol(mat)) {
    mat[i,j]=ifelse(seqa[i]==seqb[j],1,0)
  }
}
```



```{r}
mat2=mat

gap_open= -1
gap_ext=-0

imax=-1
jmax=-1
maxscore=-1

for(i in 2:nrow(mat2)){
  for(j in 2:ncol(mat2)){
    A = mat2[i-1,j-1]+ mat[i,j]
    D = mat2[i-1,j]+gap_open
    R = mat2[i,j-1]+gap_open
    
    # message(sprintf("%d %d %d", A,D,R))
    
    if (A >= D){
      if (A >= R){
        mat2[i,j]=A
      }
      else{
        mat2[i,j]=R
      }
    }else{
      if (D>=R) {
        mat2[i,j]=D
      }
      else{
        mat2[i,j]=R
      }
    }
    
    if(mat2[i,j] > maxscore){
      maxscore=mat2[i,j]
      imax=i
      jmax=j
      
    }
    
  }
}
```



```{r}
i=imax
j=jmax

a2b=integer(length=nrow(mat))

while(mat2[i,j]>0){
  a2b[i]=j
  
  top=mat2[i-1,j]
  left=mat2[i,j-1]
  aln=mat2[i-1,j-1]
  # message(sprintf("%d %d top: %d left: %d aln: %d",i,j,top,left,aln))
  
  
  if (aln > max(top,left)) {
    i=i-1
    j=j-1
  }else if( top > max(aln, left)){
    i=i-1
  }else {
    j=j-1
  }
  
}

```

```{r}
mat2[68,60]
```


```{r}
df2=data.frame(
  x=1:length(a2b),
  y=a2b
)
```

```{r}
library(ggplot2)
idx=which(mat2>0,arr.ind=TRUE)

df=data.frame(x=idx[,"row"],y=idx[,"col"],val=mat2[idx])

df %>% 
  ggplot(aes(x,y,color=val))+geom_point()+
  geom_point(data=df2,aes(x,y),color="red")
```

```{r}
df3=data.frame(
  seqa=seqa[df2$x],
  seqb=seqb[df2$y]
)
df3
```

