---
title: "Untitled"
author: "TC"
date: "3/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
source(here::here("R/isorank.R"))
source(here::here("R/mapalign.R"))
source(here::here("R/apc.R"))

```

## data

```{r}

v1= data.table::fread(cmd="grep  '^V' /home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")

w1=data.table::fread(cmd="grep  '^W' /home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")
```

```{r}
ct1=RNASSP::read_ct("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/3VRS_A.ct")

seq1=ct1$nt
```

## funcs

```{r}





read_mrf = function(filemrf) {
  myalphabet = c("a", "u", "c", "g", "-")
  len=nrow(v1)
  len_a=length(myalphabet)
  
  v1 = data.table::fread(cmd = paste("grep '^V'", filemrf))
  names(v1)[-1] = myalphabet
  
  w1 = data.table::fread(cmd = paste("grep  '^W'", filemrf))
  
w1$i=as.integer(gsub(".*\\[(.*?)\\]\\[(.*?)\\].*","\\1",w1$V1))+1

w1$j=as.integer(gsub(".*\\[(.*?)\\]\\[(.*?)\\].*","\\2",w1$V1))+1

  array_j = array(0, dim = c(len, len, len_a, len_a))
  
  for (m in 1:nrow(j)) {
    id_i = w1$i[m]
    id_j = w1$j[m]
    
    mat = matrix(as.matrix(w1[m, 2:26]), 5, 5, byrow = TRUE)
    array_j[id_i, id_j, , ] = mat
    
  }
  
  
  
  ids = expand.grid(1:nrow(v1), 1:nrow(v1)) %>% filter(Var2 > Var1) %>% arrange(Var1)
  w1_mat = as.matrix(w1[, 2:(1 + length(myalphabet) * length(myalphabet))])
  
  mat_score = sapply(1:nrow(w1_mat), function(i) {
    tmpmat = matrix(w1_mat[i,], 5, 5)
    score = sqrt(sum(tmpmat[-5,-5] ^ 2))
    return(score)
  })
  ids$score = mat_score

  mat_mrf = matrix(0, nrow(v1), nrow(v1))
  
  mat_mrf[as.matrix(ids[, c(1, 2)])] = ids[, 3]
  mat_mrf[as.matrix(ids[, c(2, 1)])] = ids[, 3]
  
  mat_apc = APC_correction(mat_mrf)
  mrf = list(
    len = len,
    h = v1,
    j = w1,
    mat_mrf = mat_mrf,
    mat_apc = mat_apc,
    array_j=array_j
  )

  return(mrf)
}
```



```{r}
mrf=read_mrf("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")
```





```{r}
# mrf_12=matrix(as.numeric(mrf$j[grep("25.*34",mrf$j$V1),2:26]),5,5)

mrf_12=array_j[26,35,,]

gg_mat(mrf_12)

```


```{r}
gg_mat(mrf$mat_mrf)

gg_mat(mrf$mat_apc)
```



```{r}

sepw=function(sep){
  wt=numeric(length=length(sep))
  
  wt[]=1
  wt[sep<=4]=0.5
  wt[sep==5]=0.75
  
  return(wt)
}

ini_SCO = function(seq, mrf, sep_x, sep_y) {
  mrf_len = nrow(mrf$h)
  SCO = matrix(0, nrow = length(seq), ncol = mrf_len)
  M=matrix(0,length(seq),mrf_len)
  for (ai in 1:length(seq)) {
    for (bi in 1:mrf_len) {
      M[]=0
      for (aj in 1:length(seq)) {
        for (bj in 1:mrf_len) {
            nt_aiaj= match(seq[c(ai,aj)],table=c("a", "u", "c", "g", "-"))
            
            if (bi>bj){
              score_a2b = mrf$array_j[bj, bi,nt_aiaj[2], nt_aiaj[1]]
            } else {
              score_a2b = mrf$array_j[bi, bj,nt_aiaj[1],nt_aiaj[2]]
            }

            sep_a = abs(ai - aj)
            sep_b = abs(bi - bj)
            sep_D = abs(sep_a - sep_b)
            sep_M = min(sep_a, sep_b)
            sep_std = sep_y * (1 + (sep_M - 2)^sep_x)
            
            M[aj,bj] =  score_a2b *  sepw(sep_M) * dnorm(sep_D, mean = 0, sd =
                                                        sep_std)
    
          }
      }
      message(ai,bi)
      SCO[ai,bi]= falign(M,length(seq),mrf_len)
    }
  }
  return(SCO)
  
}
```







## test

```{r}
seqs=seqinr::read.fasta("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.ungapped.msa")

# seqs[[2]]

seq=seqs[[1]]
```



```{r}
SCO=ini_SCO(seq,mrf=mrf,sep_x=0, sep_y=1)
```

```{r}
gg_mat(SCO)
```

```{r}
tmp =align(SCO,debug=TRUE)
```

```{r}
gg_mat(tmp)
```



