---
title: "Untitled"
author: "TC"
date: "2/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## R Markdown

```{r}
source(here::here("R/isorank.R"))
```

## test mapalign

```{r}

map1=data.table::fread(cmd= "cat ~/GIT/map_align/2pd0_A.pdb.map |grep ^CON")
l1=205

map2=data.table::fread(cmd="cat ~/GIT/map_align/3u97_A.gremlin.map |grep ^CON")
l2=77
```


```{r}
mat1=matrix(0,nrow=l1,ncol=l1)
mat2=matrix(0,nrow=l2,ncol=l2)

mat1[as.matrix(map1[,c(2,3)]+1)]=1
mat1[as.matrix(map1[,c(3,2)]+1)]=1



mat2[as.matrix(map2[,c(2,3)]+1)]=1

mat2[as.matrix(map2[,c(3,2)]+1)]=1

```





```{r}
gg_mat(mat1)

gg_mat(mat2)
```


```{r}

```



```{r}


get_Rmat = function(A, l1, l2) {
  Rv = matrix(0, nrow = l1 * l2, ncol = 1000)
  
  R=runif(l1*l2)
  
  Rv[, 1] = R
  
  for (i in 2:1000) {
    Rvnew = A_sparse %*% Rv[, i - 1]
    Rvnew = as.matrix(Rvnew)
    Rv[, i] = Rvnew / norm(Rvnew, "F")

    if (i %% 100 == 0) {
      message(i, " ", dist(rbind(Rv[, i], Rv[, i - 1])))
    }
  }
  
  Rmat = Rv2Rmat(Rv[, 1000], nrow = l1, ncol = l2)
}




```

```{r}
# Rv[,1000]


```

```{r}
gg_mat(Rmat)
```

```{r}
extract_aln = function(R) {
  Rtmp = R
  maplist=list()
  
  for (i in 1:nrow(Rtmp)) {
    max_R = max(Rtmp)
    if (max_R > 0.01) {
      


      idmax = which.max(Rtmp)
      ids = id1_to_id2(idmax, nrow(Rtmp))
      maplist=append(maplist,
                     values=list(
                       data.frame(
                       i=ids$i[[1]],
                       j=ids$j[[1]],
                       v=Rtmp[idmax]
                     )
                     ))
      message(sprintf("%d %d %d %f", i, ids$i[[1]], ids$j[[1]], Rtmp[idmax]))
      # Rtmp=Rtmp[-ids["i"],-ids["j"]]
      Rtmp[ids$i[[1]], ] = -1
      Rtmp[, ids$j[[1]]] = -1
      # gg=gg_mat(Rtmp)
      # plot(gg)
    }
    
  }
  
  return(do.call(rbind,maplist))
  # return(maplist)
}
```


```{r}
tmp=extract_aln(Rmat)
```


```{r}
u_contacts[tmp$i]

v_contacts[tmp$j]
```


```{r}
gg_mat(mat1)

gg_mat(mat2)
```

