---
title: "Untitled"
author: "TC"
date: "3/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(Rcpp)
source(here::here("R/apc.R"))
source(here::here("R/isorank.R"))
source(here::here("R/mapalign.R"))
library(patchwork)
# sourceCpp(here::here("src/mapalignR.cpp"))
```

## R Markdown

```{r}
mrf=read_mrf("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")

ct_ref=RNASSP::read_ct("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/3VRS_A.ct")

seqs=seqinr::read.fasta("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.ungapped.msa")


mrf_mat=mrf2mrf_mat(mrf)
```

##

```{r}
seq1=seqs[[1304]]


seq2mat_exp1 = function(seq1) {
  seq1.ungapped = seq1[seq1 %in% c("a", "u", "c", "g")]

  mat1 = seq2matstem(seq1.ungapped)
  
  mat_stem_gt2 = mat1
  mat_stem_gt2[mat1 < 5] = 0
  mat_stem_gt2 = mat_stem_gt2 + t(mat_stem_gt2)
  
  for (i in 1:nrow(mat_stem_gt2)) {
    tmp_colsum = sum(mat_stem_gt2[, i] > 0)
    if (tmp_colsum > 0) {
      mat_stem_gt2[, i] = mat_stem_gt2[, i] * 1 / tmp_colsum
    }
  }
  
  for (i in 1:nrow(mat_stem_gt2)) {
    tmp_rowsum = sum(mat_stem_gt2[i, ] > 0)
    if (tmp_rowsum > 0) {
      mat_stem_gt2[i, ] = mat_stem_gt2[i, ] * 1 / tmp_rowsum
    }
  }

  colnames(mat_stem_gt2) = seq1.ungapped
  mat_stem_gt2[mat_stem_gt2 < 2] = 0
  mat_stem_gt2[mat_stem_gt2 >= 2] = 1
  
  mattmp=label_stemlen(mat_stem_gt2)
  mattmp=mattmp+t(mattmp)
  
  return(mattmp)
  
}

mat1=seq2mat_exp1(seq1=seq1)

gg_mat(mat1)
# gg_mat(mat1)
# gg_mat(mat_stem_gt2)
```

```{r}
run_isorank_seq2mat = function(seq, matmrf,alpha=0.1,beta=0.7) {
  mat1 = seq2mat_exp1(seq)
  
  mat2 = matmrf
  
  Rmat = run_isorank_bpnbseq(mat1, mat2, alpha = alpha,beta=beta)
  plot(gg_mat(mat1))
  plot(gg_mat(Rmat))
  
  tmp = extract_aln(Rmat)
  
  # tmp %>% arrange(i)
  seq_aln = character(ncol(Rmat))
  seq_aln[] = "-"
  seq_aln[tmp$j] = seq1.ungapped[tmp$i]
  # seqinr::c2s(seq_aln)
  
  return(seq_aln)
  
}
```



```{r}
mat2=mrf$mat_apc

mat2[is.na(mat2)]=0

mat2[mat2<1]=0
mat2[mat2>1]=1

# colnames(mat2)=seqs[[1]]

colnames(mat2)= as.character(seqs[[1]])

rownames(mat2)=as.character(seqs[[1]])


gg_mat(mat2)

# gg_mat(mat2)+gg_mat(mat_stem_gt2)
```





```{r}
Rmat= run_isorank_bpnb(mat1, mat2,alpha=.1)

gg_mat(Rmat)
```

```{r}
# max(Rmat)

align_R(Rmat,gap_open=-0.15,gap_e=0.1)
```

```{r}


tmp=extract_aln(Rmat)

tmp %>% arrange(i)
seq_aln=character(ncol(Rmat))
seq_aln[]="-"

seq_aln[tmp$j]=seq1.ungapped[tmp$i]

seqinr::c2s(seq_aln)

```

```{r}

```


```{r}
alnseq=get_alnseq(Rmat, seq1.ungapped)
```

```{r}
bench_aln(alnseq,seqref=seqs[[1]],ct_ref)

bench_aln(seq_aln,seqref=seqs[[1]],ct_ref)

bench_aln(seqs[[1304]],seqref=seqs[[1]],ct_ref)
```

```{r}
tmp %>% arrange(i)
```


```{r}
rbind(

  seqinr::c2s(seqs[[1]]),
  seqinr::c2s(alnseq),
  seqinr::c2s(seq_aln),
  seqinr::c2s(seqs[["1303|FP929048.1/1688235-1688299"]])

)

```


## bpp

```{r}
rnafold.bpp=data.table::fread(here::here("data/set1_rfa_cln/3VRS_A_RF01734/rnafold/rnafold.bpp"))
```

```{r}
rnafold.bpp %>% 
  # filter(V3>0.7) %>% 
  ggplot(aes(V1,V2,color=V3))+
  geom_point()+coord_fixed()+
  lims(x=c(1,52),y=c(1,52)) +gg_mat(mat2)
```


```{r}

idx=as.matrix(rnafold.bpp[,1:2])

rnafold.mtx=matrix(0,52,52)

rnafold.mtx[idx]=rnafold.bpp$V3


rnafold.mtx=rnafold.mtx+t(rnafold.mtx)
```

```{r}
gg_mat(rnafold.mtx)

gg_mat(mat2)
```



```{r}
    df = as.data.frame(which(!is.na(mat2) > 0, arr.ind = TRUE))
    df$val = mat2[which(!is.na(mat2) > 0)]    
```

```{r}
ggplot(df) + geom_tile(aes(x=col, y=row, fill = val)) + coord_fixed()
```

### exp

```{r}
mat2=mrf$mat_apc

mat2[is.na(mat2)]=0
mat2[mat2<1]=0
mat2[mat2>1]=1

colnames(mat2)= as.character(seqs[[1]])
rownames(mat2)=as.character(seqs[[1]])
```

```{r}

```

```{r}
mat=seq2mat_exp1(seqs[[4]])

gg_mat(mat)+gg_mat(mat2)
```

```{r}
seq_aln=run_isorank_seq2mat(seqs[[4]],mat2,alpha=0, beta=.8)

bench_aln(seq_aln,seqref=seqs[[1]],ct_ref)
```


```{r}

seq1=seqs[[4]]
prob.spotrna=data.table::fread("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/spotrna/SPOTRNA_OUTPUT/0003.prob",header=F)

seq1.ungapped = seq1[seq1 %in% c("a", "u", "c", "g")]


prob.mat=as.matrix(prob.spotrna)
prob.mat[prob.mat>0.5]=1

prob.mat[prob.mat<0.5]=0

prob.mat=prob.mat+t(prob.mat)

gg_mat(prob.mat)



colnames(prob.mat)= seq1.ungapped

gg_mat(mat2)
```

```{r}
Rmat= run_isorank_bpnbseq(prob.mat,mat2, alpha=.1,beta=.8)

  # Rmat = run_isorank_bpnb(mat1, mat2, alpha = alpha)
  # plot(gg_mat(mat1))
  plot(gg_mat(Rmat))
  gg_mat(prob.mat)
  
  tmp = extract_aln(Rmat)
  
  # tmp %>% arrange(i)
  seq_aln = character(ncol(Rmat))
  seq_aln[] = "-"
  seq_aln[tmp$j] = seq1.ungapped[tmp$i]
bench_aln(seq_aln,seqref=seqs[[1]],ct_ref)
```


```{r}
align_R(Rmat, debug=TRUE,gap_open=-max(Rmat),gap_e=0.1) %>% 
  gg_mat()
```


```{r}
seqinr::c2s(seqs[[2]])
seqinr::c2s(seqs[[1]])
```


```{r}
seq=seqs[[8]]

seq_aln= run_isorank_seq2mat(seq=seq,matmrf=mat2,alpha=0.3)

bench_aln(seq_aln,seqref=seqs[[1]],ct_ref)
```



### bralibase


```{r}

```

