---
title: "Untitled"
author: "TC"
date: "3/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
library(Rcpp)
source(here::here("R/apc.R"))
source(here::here("R/isorank.R"))
source(here::here("R/mapalign.R"))
sourceCpp(here::here("src/mapalignR.cpp"))
```

```{r}

mrf=read_mrf("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.mrf")

ct_ref=RNASSP::read_ct("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/3VRS_A.ct")

seqs=seqinr::read.fasta("/home/tc/GIT/RNA_PKALN/data/set1_rfa_cln/3VRS_A_RF01734/tmp.ungapped.msa")


mrf_mat=mrf2mrf_mat(mrf)
```



```{r}
mrf2mrf_mat_only_Tcontact = function(mrf) {
  myalphabet = c("a", "u", "c", "g", "-")
  
  len = mrf$len
  len_a = length(myalphabet)
  
  
  mat_j = matrix(0, len * len_a, len * len_a)
  
  w1 = mrf$j
  for (m in 1:nrow(w1)) {
    id_i = w1$i[m]
    id_j = w1$j[m]
    
    id_ia = id2_to_id1(1, id_i, len_a)
    id_ja = id2_to_id1(1, id_j, len_a)
    
    mat = matrix(as.matrix(w1[m, 2:26]), 5, 5, byrow = TRUE)
    # array_j[id_i, id_j, ,] = mat
    
    if (mrf$mat_apc[id_i,id_j]<1){
      mat=matrix(0,5,5)
    }
    
    mat_j[id_ia:(id_ia + len_a - 1), id_ja:(id_ja + len_a - 1)] = mat
  }
  return(mat_j)
}
```

```{r}
mrf_mat_t=mrf2mrf_mat_only_Tcontact(mrf)

```

```{r}
mrf_mat_empty= mrf_mat

mrf_mat_empty[]=0
```

```{r}
mrf_mat_simple=mrf_mat_empty



```


```{r}


      seq=seqs[[2]]

mrf_len=mrf$len
M=matrix(0,length(seq),mrf_len)

ai=2
# aj=17
bi=2
sep_y =1
sep_x=0

sepw=function(sep){
  wt=numeric(length=length(sep))
  
  wt[]=1
  wt[sep<=4]=0.5
  wt[sep==5]=0.75
  
  return(wt)
}

      for (aj in 1:length(seq)) {
        for (bj in 1:mrf_len) {
            nt_aiaj= match(seq[c(ai,aj)],table=c("a", "u", "c", "g", "-"))
            
            if (aj==ai) next
            
            if (bj==bi) next
            
            if (bi>bj){
              score_a2b = mrf$array_j[bj, bi,nt_aiaj[2], nt_aiaj[1]]
              # score_a2b = retrieve_matj(bj, nt_aiaj[2],bi,nt_aiaj[1],mrf_mat,len_a = 5)
            } else {
              score_a2b = mrf$array_j[bi,bj,nt_aiaj[1],nt_aiaj[2]]
              # score_a2b = retrieve_matj(bi, nt_aiaj[1],bj,nt_aiaj[2],mrf_mat,len_a = 5)
            }

            sep_a = abs(ai - aj)
            sep_b = abs(bi - bj)
            sep_D = abs(sep_a - sep_b)
            sep_M = min(sep_a, sep_b)
            sep_std = sep_y * (1 + (sep_M - 2)^sep_x)
            
            if (bj==17 && aj==17){
              message(score_a2b)
              # message(dnorm(sep_D, mean = 0, sd =sep_std))
              message(sep_std)
            }
            
            M[aj,bj] =  score_a2b *  sepw(sep_M) * dnorm(sep_D, mean = 0, sd =
                                                        sep_std)
    
          }
      }


gg_mat(M)

M[is.na(M)]=0
falign_R(M,52,52)
```



```{r}

      seq=seqs[[1304]]
    exp_seq = encode_seq(seq)
    
    SCO = ini_SCO(
      seq = exp_seq$seq_int_ungapped,
      mrf_mat = mrf_mat, 
      mrf_len = mrf$len,
      sep_x = 0,
      sep_y = 1
    )
    
    align_R(SCO,debug = TRUE)
    
     gg_mat(SCO)
```


```{r}
align_R(SCO,debug = TRUE) %>% gg_mat()
```


```{r}
align(SCO,gap_ext = 0.1,gap_open = -1)
```






```{r}

SCO_mod =mod_SCO(SCO,20,exp_seq$seq_int_ungapped,mrf_mat,mrf_h=mrfh)
```

```{r}

gg_mat(SCO)
gg_mat(SCO_mod)
```

```{r}
align_R(SCO)
```


```{r}

get_alnseq = function(SCO, seq) {
  seq_aln = character(ncol(SCO))
  seq_aln[] = "-"
  SCO_pair = align_R(SCO)
  seq_aln[SCO_pair[SCO_pair > 0]] = seq[SCO_pair > 0]
  
  return(seq_aln)
  
}
# 
# SCO_pair=align_R(SCO_simple)
# seq_aln[SCO_pair[SCO_pair>0]]=seq[SCO_pair>0]
# 
#   
#   # seq_aln[SCO_pair]=myalphabet[exp_seq$seq_int_ungapped+1]
#   
#   seq_aln[SCO_pair[SCO_pair>0]]=seq[SCO_pair>0]
#   
# bench_aln(seq_aln,seqs[[1]],ct_ref)
```



```{r}
alnseq=get_alnseq(SCO, exp_seq$seq_ungapped)
```

```{r}

alnseq3=ifelse(seqs[[1304]]==seqs[[1]],"|",".")
ss=".<<<<{.((((((>>>>......((((((..))))))}.<.))))))>...."

rbind(
  ss,
  seqinr::c2s(seqs[[1]]),
  seqinr::c2s(alnseq2),
  seqinr::c2s(alnseq),
  seqinr::c2s(alnseq3),

  seqinr::c2s(seqs[["1303|FP929048.1/1688235-1688299"]]),
  ss
)



seqlist2= list(seqs[[1]],seqs[[1304]],alnseq)
```

```{r}
bench_aln_list(seqlist2, seqs[[1]],ct_ref)
```

```{r}
alnseq2=ifelse(alnseq==seqs[[1]],"|",".")
```


```{r}
data.frame(
  alnseq,
  as.character(seqs[[1]]),
  alnseq2
)
```

