---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

00
01
10
11


```{r}
mat_mrf_array=array(0, dim=c(2,2,2,2))
```

```{r}
mat_mrf_array[1,1,,]=1
mat_mrf_array[2,2,,]=1


# mat_mrf_array[1,2,,]=c(1,0,0,1)
# mat_mrf_array[2,1,,]=c(1,0,0,1)
```


```{r}

# toy, two body


get_mrf_energy = function (aseq, mrf_array){
  
  E_total=0
  E_h=0
  E_j=0
  
  for (i in 1:length(aseq)){
    for (j in 1:length(aseq)){
      if (i < j) next
      E_total = E_total + mrf_array[i, j, aseq[i],aseq[j]]
      if (i ==j){
        E_h= E_h + mrf_array[i,j,aseq[i],aseq[j]]
      }
      else{
        E_j = E_j + mrf_array[i,j,aseq[i],aseq[j]]
      }
    }
  }
  
  rslt=data.frame(
    E_total=E_total,
    E_h=E_h,
    E_j=E_j
  )
  
  return(rslt)
}
```

12 0  0.134  0.134/0.5 * 0.134/0.5 = 0.07
21 0  0.134 0.134/0.5 * 0.134/0.5 = 0.07
22 1  0.365 0.365/0.5 * 0.365/0.5 = 0.53
11 1  0.365 0.365/0.5 * 0.365/0.5 = 0.53



1_ : 0.5
_2 : 0.5

11 : 0.3/0.25 1.2
22 : 0.3/0.25 1.2
12 : 0.134/0.25 0.536
21 : 0.134/0.25 = 0.536

=========


12 0 0.134
21 0 0.134
11 1 0.356
22 1 0.356





```{r}
exp(0)/(exp(0)*2+exp(1)*2)


exp(1)/(exp(0)*2+exp(1)*2)
```


```{r}
get_mrf_energy(c(2,2), mat_mrf_array)

get_mrf_energy(c(1,2), mat_mrf_array)


get_mrf_energy(c(2,1), mat_mrf_array)


get_mrf_energy(c(1,1), mat_mrf_array)


```

