---
title: "Untitled"
author: "TC"
date: "2/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Matrix)
library(dplyr)
library(ggplot2)

source("../R/isorank.R")
library(threejs)

library(igraph)

```


```{r}
ct.ref=RNASSP::read_ct(here::here("data/toy1/ref.ct"))

ct.ss=RNASSP::read_ct(here::here("data/toy1/seq.ss.ct"))
```

```{r}
ct2mat = function(ct) {
  l1 = nrow(ct)
  mat1 = matrix(0, l1, l1)
  
  rownames(mat1) = ct$i
  
  colnames(mat1) = ct$nt
  
  linkpair = ct[ct$j > 0, c("i", "j")]
  names(linkpair) = c("from", "to")
  
  linknb = ct[ct$`i+1` > 0, c("i", "i+1")]
  names(linknb) = c("from", "to")

  mat1[as.matrix(linkpair[, c(1, 2)])] = 1
  mat1[as.matrix(linkpair[, c(2, 1)])] = 1
  
  # mat1[as.matrix(linknb[, c(1, 2)])] = 1
  # mat1[as.matrix(links[, c(2, 1)])] = 1
  return(mat1)
}
```

```{r}


mat1=ct2mat(ct.ss)

g1=mat2graph(mat1)
ig1=graph_from_data_frame(d=g1$edges,vertices=g1$nodes)

mat2=ct2mat(ct.ref)

g2=mat2graph(mat2)
ig2=graph_from_data_frame(d=g2$edges,vertices=g2$nodes)
```

```{r}
gg_mat(mat1)
```


## vis
```{r}
graphjs(ig1)

graphjs(ig2)
```




## isorank_directed

```{r}
l1=nrow(mat1)
l2=nrow(mat2)


```


```{r}
A_bp=get_matA(mat1,mat2)

A_nb=get_A_nb(mat1,mat2)


```

```{r}
rmatv=get_Rmatv(A_nb,l1,l2,debug=TRUE)
```

```{r}
rmat=Rv2Rmat(rmatv[,1000],l1,l2)
```

```{r}
gg_mat(rmat)
```


```{r}

do_it=function(A_sparse,l1,l2,iteration,debug=FALSE){
  Rmatv=get_Rmatv(A_sparse,l1,l2,iteration,debug)
  Rmat=matrix(Rmatv[, iteration], nrow=l1,ncol=l2)
  # df=extract_aln(Rmat)
  # df
  return(Rmat)
}


do_it_wrapper = function(alpha, A_bp, A_nb) {
  # alpha = alphh
  # beta = .4
  l1 = nrow(mat1)
  l2 = nrow(mat2)

  # A_all = alpha * A_bp + beta * A_nb + (1 - alpha - beta) * A_seq
  A_all= alpha *A_bp + (1-alpha) * A_nb
  rmat = do_it(A_all, l1, l2, iteration = 10000, debug = FALSE)
  gg_mat(rmat)
}


run_isorank_bpnb=function(mat1,mat2){
  
}

```

```{r}
do_it_wrapper(0.5, A_bp,A_nb)
```



