---
title: "Untitled"
author: "TC"
date: "2/24/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## funcs

```{r}
library(ggplot2)
gg_mat=function(mat){
  df=as.data.frame(as.table(mat))
  ggplot(df,aes(Var1,Var2,fill=Freq))+geom_tile()+coord_fixed()
}
```


## isorank

```{r}
nodes=data.frame(
  id=1:10,
  label=1:10
)

links=data.frame(
  from=c(1:9,3,4),
  to=c(2:10,8,7)
)
```


```{r}
visNetwork::visNetwork(nodes, links, width="100%", height="400px")
```



```{r}

set.seed(42)

mat1=matrix(0, 5,5)

mat2=matrix(0, 6,6)

mat1[sample(1:length(mat1),5)]= 1



mat1=pmax(mat1,t(mat1))

mat2[sample(1:length(mat2),5)]= 1

mat2=pmax(mat2,t(mat2))
# mat1
gg_mat(mat1)

gg_mat(mat2)
# image(mat1)


```





```{r}
R=runif(nrow(mat1))

Rv=matrix(0,nrow=nrow(mat1),ncol=100)

Rv[,1]=R

for(i in 2:100){
  Rvnew= mat1 %*% Rv[,i-1]
  Rv[,i] = Rvnew/norm(Rvnew, "F") 
  
  message(i," ", dist(rbind(Rv[,i],Rv[,i-1])))
}
```

```{r}
eigen(mat1)
```


## construct A

```{r}
mat1

mat2
```

```{r}
l1=nrow(mat1)
l2=nrow(mat2)

A=matrix(0,nrow=l1*l2,ncol=l1*l2)


```


```{r}
id1_to_id2=function(id,dim){
  # j = id %/% (dim +1)+1
  i = id %% (dim)
  j=ceiling(id/dim)
  i[i==0]=dim
  return(data.frame(i=i,j=j))
}

id2_to_id1=function(i,j,dim){
  return((j-1)*dim+i)
}
```




```{r}
for(i in 1:l1){
  for (j in 1:l2){
    for(u in 1:l1){
      u_contacts= sum(mat1[u,])
      for(v in 1:l2){
        v_contacts=sum(mat2[v,])
        if (mat1[i,u]>0 && mat2[j,v] >0){
          
          id_row=id2_to_id1(i,j,l1)
          id_col=id2_to_id1(u,v,l1)
          
          A[id_row,id_col]=1/(u_contacts*v_contacts)
          
          # A[(i-1)*l2+j, (u-1)*l2+v]=1/(u_contacts*v_contacts)

        }
      }
    }
  }
}
```

```{r}
A.eig=eigen(A)
```

```{r}
A.eig$vectors[,1]
```


```{r}
R = matrix(Re(A.eig$vectors[,1]),nrow=nrow(mat1))
```

```{r}
R
```


```{r}
gg_mat(R)
```


```{r}
extract_aln=function(R){
  Rtmp=R
  
  for(i in 1:nrow(Rtmp)){
    idmax=which.max(Rtmp)
    ids=id1_to_id2(idmax,nrow(Rtmp))
    message(sprintf("%d %d %d %f",i, ids$i[[1]],ids$j[[1]], Rtmp[idmax]))
    # Rtmp=Rtmp[-ids["i"],-ids["j"]]
    Rtmp[ids$i[[1]],]=0
    Rtmp[,ids$j[[1]]]=0
  }
}
```


```{r}
colSums(A)
```


```{r}
gg_mat(A)
```


```{r}
gg_mat(mat1)

gg_mat(mat2)
```


```{r}

R.filt=R

R.filt[R<0.18]=0

gg_mat(R.filt)
```


```{r}
extract_aln(R)
# mat1
# mat2

```

