---
title: "Untitled"
author: "TC"
date: "3/11/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source(here::here("R/isorank.R"))
library(tidyverse)

```

## R Markdown


```{r}
mrf=array(0,dim=c(10,10,5,5))
```

```{r}
mrf[4,5,1,2]=1
mrf[4,5,2,1]=1
mrf[4,5,3,4]=1
mrf[4,5,4,3]=1

mrf[5,4,,]=mrf[4,5,,]
```

```{r}
mrf[4,5,,]
```

```{r}
mrf_sq=matrix(0,10,10)

for (i in 1:10){
  for (j in 1:10){
    mrf_sq[i,j]= sqrt(sum(mrf[i,j,,]^2))
  }
}
```

```{r}

randomseqs= lapply(1:1000, function(i){
  seq= sample(1:4, size=10, replace=TRUE)
})


# gg_mat(mrf_sq)

```

```{r}
score_randomseqs = sapply(randomseqs, function(seq){
  score_pair=0;
  for(i in 1:length(seq)){
    for(j in 1:length(seq)){
      score_pair = score_pair + mrf[i,j,seq[i],seq[j]]
    }
  }
  return(score_pair)
})
```

```{r}
plot(score_randomseqs)
```

```{r}
randomseqs_1 = randomseqs[score_randomseqs>1]
```

```{r}
randomseqs_1[[1]]

randomseqs_1[[2]]

randomseqs_1[[3]]
```


```{r}
mrf_h=matrix(0,nrow=10,ncol=5)
```

```{r}

```



```{r}




```

